spring:
  application:
    name: lims-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_09_lims?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: 'root'
    password: 'Highgoal123!'
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
      date-format: 'yyyy-MM-dd HH:mm:ss'
      time-zone: GMT+8 